# Generated by Django 5.1.7 on 2025-04-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togCul', '0003_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
