# Generated by Django 5.1.7 on 2025-04-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togCul', '0004_alter_membership_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.AddField(
            model_name='customuser',
            name='membershipStatus',
            field=models.IntegerField(choices=[(0, 'No Membership'), (1, 'Pending Approval'), (2, 'Approved')], default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='membershipType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
