# Generated by Django 5.1.7 on 2025-04-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togCul', '0005_delete_membership_customuser_membershipstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
