# Generated by Django 5.1.7 on 2025-04-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togCul', '0015_event_event_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Events',
        ),
    ]
