# Generated by Django 5.1.7 on 2025-04-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togCul', '0016_rename_event_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_date',
        ),
    ]
