# Generated by Django 5.1.7 on 2025-04-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togCul', '0017_remove_events_event_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Add_Events',
        ),
    ]
