# Generated by Django 5.1.7 on 2025-04-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togCul', '0018_rename_events_add_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_Events',
            new_name='Events',
        ),
    ]
