# Generated by Django 5.1.7 on 2025-04-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togCul', '0019_rename_add_events_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='All_Events',
        ),
    ]
