# Generated by Django 5.1.7 on 2025-04-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togCul', '0021_alter_all_events_options_remove_all_events_event_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_events',
            options={'verbose_name': 'All Event', 'verbose_name_plural': 'All Events'},
        ),
    ]
