# Generated by Django 5.1.7 on 2025-04-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togCul', '0022_alter_all_events_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_events',
            options={},
        ),
    ]
