# Generated by Django 5.1.7 on 2025-04-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togCul', '0023_alter_all_events_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All_Events',
            new_name='AllEvents',
        ),
        migrations.AlterModelOptions(
            name='allevents',
            options={'verbose_name': 'AllEvent', 'verbose_name_plural': 'AllEvents'},
        ),
    ]
