# Generated by Django 5.2 on 2025-04-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("togCul", "0025_digitalcontent_registereddigitalcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalcontent",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="digital_content_images/"
            ),
        ),
    ]
