# Generated by Django 5.2 on 2025-04-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("togCul", "0026_digitalcontent_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="interest_name",
            field=models.CharField(default="Not Specified", max_length=100),
        ),
    ]
