# Generated by Django 5.2 on 2025-04-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("togCul", "0027_customuser_interest_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="interest_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="interests",
            field=models.JSONField(default=list),
        ),
    ]
