# Generated by Django 5.1.6 on 2025-03-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togCul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
