# Generated by Django 5.1.6 on 2025-03-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togCul', '0002_member_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
