# Generated by Django 5.1.6 on 2025-04-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togCul', '0003_alter_member_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField()),
                ('attendees', models.IntegerField(default=0)),
            ],
        ),
    ]
